### ISSUE TITLE
Important edit!

### ISSUE THREAD

**Issue by XionioXMaster** [eccentricdevotion/DyeableWater#3]
If you use a plugin for suit armor, for example, oraxen, which uses leather armor to replace it with custom options, you can make simple leather armor from the armor that is installed, need disable third-party NBT coloring

![image](https://user-images.githubusercontent.com/86433158/160092283-44ee5f1d-3616-4e33-83c2-e7199c2e9e4c.png)
![image](https://user-images.githubusercontent.com/86433158/160092323-871ed118-b169-48af-9817-4938bcd948ef.png)

**Comment by eccentricdevotion** [comment]
You can no longer dye custom armour in v1.0.8, update from the Spigot page :)
